/*
 * Copyright (c) Open Metaverse Foundation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Reflection;

namespace Simian.Scripting.Linden
{
    public partial class LindenApi : ISceneModule, IScriptApi
    {
        #region Method Names

        private HashSet<string> m_methods = new HashSet<string>
        {
            "llAbs",
            "llAcos",
            "llAddToLandBanList",
            "llAddToLandPassList",
            "llAdjustSoundVolume",
            "llAllowInventoryDrop",
            "llAngleBetween",
            "llApplyImpulse",
            "llApplyRotationalImpulse",
            "llAsin",
            "llAtan2",
            "llAttachToAvatar",
            "llAvatarOnSitTarget",
            "llAxes2Rot",
            "llAxisAngle2Rot",
            "llBase64ToInteger",
            "llBase64ToString",
            "llBreakAllLinks",
            "llBreakLink",
            "llCeil",
            "llClearCameraParams",
            "llClearPrimMedia",
            "llCloseRemoteDataChannel",
            "llCloud",
            "llCollisionFilter",
            "llCollisionSound",
            "llCollisionSprite",
            "llCos",
            "llCreateLink",
            "llCSV2List",
            "llDeleteSubList",
            "llDeleteSubString",
            "llDetachFromAvatar",
            "llDetectedGrab",
            "llDetectedGroup",
            "llDetectedKey",
            "llDetectedLinkNumber",
            "llDetectedName",
            "llDetectedOwner",
            "llDetectedPos",
            "llDetectedRot",
            "llDetectedTouchBinormal",
            "llDetectedTouchFace",
            "llDetectedTouchNormal",
            "llDetectedTouchPos",
            "llDetectedTouchST",
            "llDetectedTouchUV",
            "llDetectedType",
            "llDetectedVel",
            "llDialog",
            "llDie",
            "llDumpList2String",
            "llEdgeOfWorld",
            "llEjectFromLand",
            "llEmail",
            "llEscapeURL",
            "llEuler2Rot",
            "llFabs",
            "llFloor",
            "llForceMouselook",
            "llFrand",
            "llGetAccel",
            "llGetAgentInfo",
            "llGetAgentLanguage",
            "llGetAgentSize",
            "llGetAlpha",
            "llGetAndResetTime",
            "llGetAnimation",
            "llGetAnimationList",
            "llGetAttached",
            "llGetBoundingBox",
            "llGetCameraPos",
            "llGetCameraRot",
            "llGetCenterOfMass",
            "llGetColor",
            "llGetCreator",
            "llGetDate",
            "llGetEnergy",
            "llGetForce",
            "llGetFreeMemory",
            "llGetFreeURLs",
            "llGetGeometricCenter",
            "llGetGMTclock",
            "llGetHTTPHeader",
            "llGetInventoryCreator",
            "llGetInventoryKey",
            "llGetInventoryName",
            "llGetInventoryNumber",
            "llGetInventoryPermMask",
            "llGetInventoryType",
            "llGetKey",
            "llGetLandOwnerAt",
            "llGetLinkKey",
            "llGetLinkName",
            "llGetLinkNumber",
            "llGetLinkPrimitiveParams",
            "llGetListEntryType",
            "llGetListLength",
            "llGetLocalPos",
            "llGetLocalRot",
            "llGetMass",
            "llGetNextEmail",
            "llGetNotecardLine",
            "llGetNumberOfNotecardLines",
            "llGetNumberOfPrims",
            "llGetNumberOfSides",
            "llGetObjectDesc",
            "llGetObjectDetails",
            "llGetObjectMass",
            "llGetObjectName",
            "llGetObjectPermMask",
            "llGetObjectPrimCount",
            "llGetOmega",
            "llGetOwner",
            "llGetOwnerKey",
            "llGetParcelDetails",
            "llGetParcelFlags",
            "llGetParcelMaxPrims",
            "llGetParcelPrimCount",
            "llGetParcelPrimOwners",
            "llGetPermissions",
            "llGetPermissionsKey",
            "llGetPos",
            "llGetPrimitiveParams",
            "llGetPrimMediaParams",
            "llGetRegionAgentCount",
            "llGetRegionCorner",
            "llGetRegionFlags",
            "llGetRegionFPS",
            "llGetRegionName",
            "llGetRegionTimeDilation",
            "llGetRootPosition",
            "llGetRootRotation",
            "llGetRot",
            "llGetScale",
            "llGetScriptName",
            "llGetScriptState",
            "llGetSimulatorHostname",
            "llGetStartParameter",
            "llGetStatus",
            "llGetSubString",
            "llGetSunDirection",
            "llGetTexture",
            "llGetTextureOffset",
            "llGetTextureRot",
            "llGetTextureScale",
            "llGetTime",
            "llGetTimeOfDay",
            "llGetTimestamp",
            "llGetTorque",
            "llGetUnixTime",
            "llGetVel",
            "llGetWallclock",
            "llGiveInventory",
            "llGiveInventoryList",
            "llGiveMoney",
            "llGodLikeRezObject",
            "llGround",
            "llGroundContour",
            "llGroundNormal",
            "llGroundRepel",
            "llGroundSlope",
            "llHTTPRequest",
            "llHTTPResponse",
            "llInsertString",
            "llInstantMessage",
            "llIntegerToBase64",
            "llKey2Name",
            "llLinkParticleSystem",
            "llList2CSV",
            "llList2Float",
            "llList2Integer",
            "llList2Key",
            "llList2List",
            "llList2ListStrided",
            "llList2Rot",
            "llList2String",
            "llList2Vector",
            "llListen",
            "llListenControl",
            "llListenRemove",
            "llListFindList",
            "llListInsertList",
            "llListRandomize",
            "llListReplaceList",
            "llListSort",
            "llListStatistics",
            "llLoadURL",
            "llLog",
            "llLog10",
            "llLookAt",
            "llLoopSound",
            "llLoopSoundMaster",
            "llLoopSoundSlave",
            "llMapDestination",
            "llMD5String",
            "llMessageLinked",
            "llMinEventDelay",
            "llModifyLand",
            "llModPow",
            "llMoveToTarget",
            "llOffsetTexture",
            "llOpenRemoteDataChannel",
            "llOverMyLand",
            "llOwnerSay",
            "llParcelMediaCommandList",
            "llParcelMediaQuery",
            "llParseString2List",
            "llParseStringKeepNulls",
            "llParticleSystem",
            "llPassCollisions",
            "llPassTouches",
            "llPlaySound",
            "llPlaySoundSlave",
            "llPow",
            "llPreloadSound",
            "llPushObject",
            "llRegionSay",
            "llReleaseControls",
            "llReleaseURL",
            "llRemoteDataReply",
            "llRemoteLoadScriptPin",
            "llRemoveFromLandBanList",
            "llRemoveFromLandPassList",
            "llRemoveInventory",
            "llRemoveVehicleFlags",
            "llRequestAgentData",
            "llRequestInventoryData",
            "llRequestPermissions",
            "llRequestSecureURL",
            "llRequestSimulatorData",
            "llRequestURL",
            "llResetLandBanList",
            "llResetLandPassList",
            "llResetOtherScript",
            "llResetScript",
            "llResetTime",
            "llRezAtRoot",
            "llRezObject",
            "llRot2Angle",
            "llRot2Axis",
            "llRot2Euler",
            "llRot2Fwd",
            "llRot2Left",
            "llRot2Up",
            "llRotateTexture",
            "llRotBetween",
            "llRotLookAt",
            "llRotTarget",
            "llRotTargetRemove",
            "llRound",
            "llSameGroup",
            "llSay",
            "llScaleTexture",
            "llScriptDanger",
            "llSendRemoteData",
            "llSensor",
            "llSensorRemove",
            "llSensorRepeat",
            "llSetAlpha",
            "llSetBuoyancy",
            "llSetCameraAtOffset",
            "llSetCameraEyeOffset",
            "llSetCameraParams",
            "llSetClickAction",
            "llSetColor",
            "llSetDamage",
            "llSetForce",
            "llSetForceAndTorque",
            "llSetHoverHeight",
            "llSetInventoryPermMask",
            "llSetLinkAlpha",
            "llSetLinkColor",
            "llSetLinkPrimitiveParams",
            "llSetLinkPrimitiveParamsFast",
            "llSetLinkTexture",
            "llSetLinkTextureAnim",
            "llSetLocalRot",
            "llSetPrimMediaParams",
            "llSetObjectDesc",
            "llSetObjectName",
            "llSetObjectPermMask",
            "llSetParcelMusicURL",
            "llSetPayPrice",
            "llSetPos",
            "llSetPrimitiveParams",
            "llSetRemoteScriptAccessPin",
            "llSetRot",
            "llSetScale",
            "llSetScriptState",
            "llSetSitText",
            "llSetSoundQueueing",
            "llSetSoundRadius",
            "llSetStatus",
            "llSetText",
            "llSetTexture",
            "llSetTextureAnim",
            "llSetTimerEvent",
            "llSetTorque",
            "llSetTouchText",
            "llSetVehicleFlags",
            "llSetVehicleFloatParam",
            "llSetVehicleRotationParam",
            "llSetVehicleType",
            "llSetVehicleVectorParam",
            "llSHA1String",
            "llShout",
            "llSin",
            "llSitTarget",
            "llSleep",
            "llSqrt",
            "llStartAnimation",
            "llStopAnimation",
            "llStopHover",
            "llStopLookAt",
            "llStopMoveToTarget",
            "llStopSound",
            "llStringLength",
            "llStringToBase64",
            "llStringTrim",
            "llSubStringIndex",
            "llTakeControls",
            "llTan",
            "llTarget",
            "llTargetOmega",
            "llTargetRemove",
            "llTeleportAgentHome",
            "llToLower",
            "llToUpper",
            "llTriggerSound",
            "llTriggerSoundLimited",
            "llUnescapeURL",
            "llUnSit",
            "llVecDist",
            "llVecMag",
            "llVecNorm",
            "llVolumeDetect",
            "llWater",
            "llWhisper",
            "llWind",
            "llXorBase64StringsCorrect",
        };

        #endregion Method Names

        public int CountMethods()
        {
            int count = 0;

            foreach (MethodInfo method in this.GetType().GetMethods())
            {
                object[] scriptMethodAttribute = method.GetCustomAttributes(typeof(ScriptMethodAttribute), false);
                if (scriptMethodAttribute.Length > 0 && m_methods.Contains(method.Name))
                    ++count;
            }

            return count;
        }
    }
}
